Documentation/public-api/pom.xml
=> IVYPORTAL-16465 Analyze LTS 8 for XSS Vulnerabilities

Documentation/public-api/pom.xml
This reverts commit 607134ff8b09e5e4ffaf73eaa935b4ce187578a8.
=> Revert "IVYPORTAL-16465 Analyze LTS 8 for XSS Vulnerabilities"

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml, AxonIvyPortal/portal/webContent/resources/js/dashboard.js
- Fix error that make JS function not work correctly
=> IVYPORTAL-16662: Quick Search in Dashboard Case list LTS

Documentation/maven/pom.xml
Reverts axonivy-market/portal#595
=> Revert "IVYPORTAL-16804 Various or urgent requests in IVYPORTAL - S257 > IVYP…"

Documentation/maven/pom.xml
Reverts axonivy-market/portal#613
=> Revert "Revert "IVYPORTAL-16804 Various or urgent requests in IVYPORTAL - S257 > IVYP…""

Documentation/maven/pom.xml
Reverts axonivy-market/portal#615
=> Revert "Revert "Revert "IVYPORTAL-16804 Various or urgent requests in IVYPORTAL - S257 > IVYP…"""

build/gui-test/Jenkinsfile
This reverts commit e46f624bb7b87bc8ff73f0aecea21c7246c7caeb.
=> Revert "IVYPORTAL-16745: CaseReadAllOwnRoleInvolved Logics"

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java
=> IVYPORTAL-16809: Edit permission does not show pre-permission

Documentation/maven/pom.xml
This reverts commit ff8315cba559548fded284eadb84856c6570de59.
=> Revert "IVYPORTAL-16851 Create Release 11.3.0-m257 (#639)"

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java
- Changed approach: find each permission instead of find all permissions at once
=> IVYPORTAL-16809 Edit permission does not show pre-permission

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/WelcomeEditWidgetNewDashboardPage.java, AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserProfileBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/WelcomeDashboardWidget.java
- Fix GUI test
- Fix error when create new welcome widget
- Fix error when open my profile
=> IVYPORTAL-16765 Primefaces 13

Documentation/maven/pom.xml
Reverts axonivy-market/portal#652
=> Revert "Update pom.xml"

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java
=> IVYPORTAL-16765 Upgrade to Primefaces 13

Documentation/maven/pom.xml
Reverts axonivy-market/portal#660
=> Revert "Update pom.xml for Portal version 11.3.0-m257.1"

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/ComplexFilterHelper.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/WaitHelper.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseEditWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskEditWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardCaseWidgetFilterTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardEditCaseWidgetTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardEditTaskWidgetTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetActionTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetFilterTest.java, build/gui-test-new-dashboard/Jenkinsfile
PR for Feature/ivyportal 16355
=> Feature/ivyportal 16355 task widget complex filters g UI tests & screenshots 11

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
- Fixed failed test related to breadcrumb
=> IVYPORTAL-16533 Make GUI test more stable

AxonIvyPortal/portal/webContent/resources/js/portal.js
=> IVYPORTAL-16872 AJAX indicator block the error dialog

AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/dto/IvyNotificationChannelDTO.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/UserProfile/UserProfile.xhtml
=> IVYPORTAL-16961-User-setting-notification-bug

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/AdditionalComponentsScreenshotTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardNotificationWidgetPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardConfigurationTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardRestoreConfigurationTest.java
…ult-dashboard-template-check-performance - Fix GUI test
=> IVYPORTAL-16987-Adapt-GUI-test-screenshot-test-due-to-update-new-default-dashboard-template-check-performance - Fix GUI test

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml, AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
- Reduce to 1 request
- Adapt empty message when using quick search
- Added ajax indicator when processing quick search
=> IVYPORTAL-16863 Quick Search Improvements

AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/MenuView.java
=> IVYPORTAL-16948 Leave task warning for internal menu item

AxonIvyPortal/PortalKit/src/ch/ivy/addon/portalkit/ivydata/service/impl/CaseService.java, AxonIvyPortal/PortalKit/src/ch/ivy/addon/portalkit/util/PermissionUtils.java, AxonIvyPortal/portal-components/src/com/axonivy/portal/components/ivydata/service/impl/CaseService.java, AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/PermissionUtils.java
=> IVYPORTAL-16745 Adapt CaseReadAllOwnRoleInvolved Permission

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardDetailsEditPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskEditWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/StickyNavigationDashboardTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardConfigurationTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/globalsearch/SearchTaskTest.java
=> IVYPORTAL-16958 Various or urgent requests in IVYPORTAL - S259

Documentation/maven/pom.xml
Reverts axonivy-market/portal#766
=> Revert "update pom.xml for Portal 11.4.0-m259"

AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
- Implement load charts after widgets
=> IVYPORTAL-16987 Improve performance when load the new dashboard

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskEditWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/QuickSearchTest.java, AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml, AxonIvyPortal/portal/webContent/resources/js/portal.js
=> IVYPORTAL-16949   Quick Search Enhancements 2 LE

Documentation/portal-guide/source/portal-developer-guide/installation/index.rst
=> IVYPORTAL-17089 Automate migrate dashboard's process widget type

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/QuickSearchTest.java
=> IVYPORTAL-16949 Quick Search Enhancements 2

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
=> IVYPORTAL-17168 add null check to DashboardBean

Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst, Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-process-widget.rst, Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-task-widget.rst, Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
=> Document/ivyportal 16657 deactivate dashboard widget icons info & extend lts

AxonIvyPortal/PortalKitTestHelper/.settings/ch.ivyteam.ivy.designer.prefs, AxonIvyPortal/PortalKitTestHelper/.settings/org.eclipse.jdt.core.prefs, AxonIvyPortal/PortalKitTestHelper/.settings/org.eclipse.wst.common.project.facet.core.xml, AxonIvyPortal/PortalTest/.settings/ch.ivyteam.ivy.designer.prefs, AxonIvyPortal/PortalTest/.settings/org.eclipse.jdt.core.prefs, AxonIvyPortal/PortalTest/.settings/org.eclipse.wst.common.project.facet.core.xml, AxonIvyPortal/portal-components/.settings/ch.ivyteam.ivy.designer.prefs, AxonIvyPortal/portal-components/.settings/org.eclipse.jdt.core.prefs, AxonIvyPortal/portal-components/.settings/org.eclipse.wst.common.project.facet.core.xml, AxonIvyPortal/portal-selenium-test/.settings/ch.ivyteam.ivy.designer.prefs, AxonIvyPortal/portal-selenium-test/.settings/org.eclipse.jdt.core.prefs, AxonIvyPortal/portal-selenium-test/.settings/org.eclipse.wst.common.project.facet.core.xml, AxonIvyPortal/portal/.settings/ch.ivyteam.ivy.designer.prefs, AxonIvyPortal/portal/.settings/org.eclipse.jdt.core.prefs, AxonIvyPortal/portal/.settings/org.eclipse.wst.common.project.facet.core.xml, Showcase/InternalSupport/.settings/ch.ivyteam.ivy.designer.prefs, Showcase/InternalSupport/.settings/org.eclipse.jdt.core.prefs, Showcase/InternalSupport/.settings/org.eclipse.wst.common.project.facet.core.xml, Showcase/portal-components-examples/.settings/ch.ivyteam.ivy.designer.prefs, Showcase/portal-components-examples/.settings/org.eclipse.jdt.core.prefs, Showcase/portal-components-examples/.settings/org.eclipse.wst.common.project.facet.core.xml, Showcase/portal-developer-examples/.settings/ch.ivyteam.ivy.designer.prefs, Showcase/portal-developer-examples/.settings/org.eclipse.jdt.core.prefs, Showcase/portal-developer-examples/.settings/org.eclipse.wst.common.project.facet.core.xml, Showcase/portal-user-examples/.settings/ch.ivyteam.ivy.designer.prefs, Showcase/portal-user-examples/.settings/org.eclipse.jdt.core.prefs, Showcase/portal-user-examples/.settings/org.eclipse.wst.common.project.facet.core.xml
=> IVYPORTAL-17233-convert-project-to-114004

build/document-screenshot-selenide/Jenkinsfile, build/document-screenshot/Jenkinsfile, build/gui-test-cluster/Jenkinsfile, build/gui-test-new-dashboard/Jenkinsfile, build/gui-test/Jenkinsfile, build/integration/Jenkinsfile
=> IVYPORTAL-17234-Release-11.4.0-m261

Documentation/Jenkinsfile
=> IVYPORTAL-17234-Release-11.4.0-m261-fix-document-permission

Documentation/Jenkinsfile
Fix permission denied when delete workspace follow guide from https://stackoverflow.com/questions/63573164/jenkins-git-clean-permission-denied-error
=> IVYPORTAL-17203 Update Portal to Java 21

Showcase/portal-developer-examples/processes/Start Processes/ExamplePortalStart.p.json
=> IVYPORTAL-16892 Hide case creator info

AxonIvyPortal/portal-selenium-test/resources/testFile/default-dashboard-quicksearch.json, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessEditWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/QuickSearchTest.java, AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/CompactProcessDashboardWidget.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/ProcessDashboardWidget.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/process/NameColumnModel.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardWidgetType.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardProcessSearchCriteria.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/ProcessWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidgetConfiguration/ProcessWidgetConfiguration.xhtml, build/gui-test-new-dashboard/Jenkinsfile
Reverts axonivy-market/portal#918
=> Revert "Feature/ivyportal 16656 quick search in processes widget lts"

build/document-screenshot-selenide/Jenkinsfile, build/document-screenshot/Jenkinsfile, build/gui-test-new-dashboard/Jenkinsfile, build/integration/Jenkinsfile
=> IVYPORTAL-17356-Create-sprint-release-for-LE

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessEditWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/QuickSearchTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardEditCaseWidgetTest.java
=> IVYPORTAL-17430-Fix-GUI-Test-LE

AxonIvyPortal/portal/webContent/resources/css/portal.css, AxonIvyPortal/portal/webContent/resources/js/portal.js, Documentation/portal-guide/source/portal-user-guide/accessibility/documents/shortcuts.csv, Documentation/portal-guide/source/portal-user-guide/accessibility/index.rst, Documentation/portal-guide/source/portal-user-guide/index.rst
=> IVYPORTAL-17254 Implement navigation with short cuts - All Portal Site

AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
…ortal-Version-10-LE - Fix redundant space
=> IVYPORTAL-17270 Spacing in portal menu after removing items Portal LE

AxonIvyPortal/portal-components/cms/cms_de.yaml, AxonIvyPortal/portal-components/cms/cms_en.yaml, AxonIvyPortal/portal-components/cms/cms_es.yaml, AxonIvyPortal/portal-components/cms/cms_fr.yaml, AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/ProcessViewer/ProcessViewer.xhtml, AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CustomDashboardWidget/CustomDashboardWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CustomIFrameWidget/CustomIFrameWidget.xhtml, AxonIvyPortal/portal/webContent/layouts/restricted/AbstractTaskTemplate.xhtml, AxonIvyPortal/portal/webContent/layouts/restricted/IFrameTaskTemplate.xhtml
=> IVYPORTAL-17250 Implement an title element for iframes

AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml, AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/ProcessViewer/ProcessViewer.xhtml, AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/CaseDocuments/CaseDocuments.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskDocuments/TaskDocuments.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ColumnManagement/ColumnManagement.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardReorder/DashboardReorder.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/StartCell.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/SelectDeputy.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDescription/CaseItemDescription.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseWidget/CaseWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SecurityMemberDisplayName/SecurityMemberDisplayName.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskAnalysisWidget/TaskAnalysisWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItem/TaskAction.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDescription/TaskItemDescription.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskWidget/TaskWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/filter/AdvancedFilter/AdvancedFilter.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/statistic/StatisticDashboardWidget/StatisticDashboardWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/filter/AdvancedFilter/AdvancedFilter.xhtml, AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NewsWidget/NewsItem.xhtml, AxonIvyPortal/portal/webContent/layouts/includes/chatAssigneeSelection.xhtml, AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
…ar-All-Portal-Sites-10 - Update all link aria-label
=> ivyportal 17251 implement elements with i ds for header task bar all portal sites 10

AxonIvyPortal/PortalTest/src_test/portal/guitest/common/BaseTest.java, AxonIvyPortal/PortalTest/src_test/portal/guitest/test/GlobalGrowlTest.java, AxonIvyPortal/PortalTest/src_test/portal/guitest/test/LanguageSettingTest.java, AxonIvyPortal/PortalTest/src_test/portal/guitest/userexample/test/LeaveRequestTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/QuickSearchTest.java
=> Bug/ivyportal 17514 fix g UI tests lts

AxonIvyPortal/portal/cms/cms.yaml, AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CustomWidgetConfiguration/CustomWidgetConfiguration.xhtml
=> IVYPORTAL-16563 Rename custom widget process start option

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/widget/CategoryFilterColumn/CategoryFilterColumn.xhtml
- Remove load when open filter dialog
=> IVYPORTAL-17453 Improve performance when open case filter dialog

AxonIvyPortal/portal/processes/Functional Processes/ChangePassword.p.json
=> IVYPORTAL-17183 Adapt process deprecate on LE

AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskActionBean.java
=> IVYPORTAL-17553: TaskWriteExpiryTimestamp does not work as expected

AxonIvyPortal/portal-selenium-test/resources/testFile/custom-case-details-with-url.json, AxonIvyPortal/portal-selenium-test/resources/testFile/custom-user-menu.json, AxonIvyPortal/portal-selenium-test/resources/testFile/task-details-custom-iframe.json, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java, Showcase/portal-developer-examples/resources/files/variables.Portal.CaseDetails.json, Showcase/portal-developer-examples/resources/files/variables.Portal.TaskDetails.json
=> IVYPORTAL-17649 Create sprint release

AxonIvyPortal/PortalTest/src_test/portal/guitest/test/TaskDetailsTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetActionTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskActionTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskDetailsTest.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/PortalPermission.java
- adapt failed tests based on IVYPORTAL-17553 after merge
=> IVYPORTAL-15714-SELENIDE-LTS-Portal-test

AxonIvyPortal/portal-selenium-test/resources/testFile/custom-case-details-with-url.json, AxonIvyPortal/portal-selenium-test/resources/testFile/task-details-custom-iframe.json, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalCasesScreenshotTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalTaskScreenshotTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
- adapt link to make screenshot pass due to Firefox error
=> IVYPORTAL-17656-Adapt-screenshot-test-for-release-10-due-to-Firefox

AxonIvyPortal/PortalTest/src_test/portal/guitest/test/TaskDetailsTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskDetailsTest.java
- disable test to make build pass
=> Temporary-ignore-test-to-make-build-green

AxonIvyPortal/portal-selenium-test/customized_pom.xml, build/gui-test-new-dashboard/Jenkinsfile
- implement retry mechanism for GUI test
=> IVYPORTAL-17660-Implement-retry-mechanism-for-GUI-test-on-LE

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java
=> ci-cd-fix-gui-test-release_10

AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/TaskService.java, build/gui-test-new-dashboard/Jenkinsfile
- Adapt API currentUserOrHisRolesAreInvolved()
=> IVYPORTAL-17671 Adapt currentUserOrHisRolesAreInvolved API for Task

Documentation/maven/pom.xml
Reverts axonivy-market/portal#1058
=> Revert "Update doc version for portal 12.0.0-m264"

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalCasesScreenshotTest.java
- remove comment for screenshot
=> remove-comment-from-PortalCasesScreenshotTest

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskDetailsTest.java
=> remove-disabled-test-after-fix-bug

AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_es.yaml
- cms vom to von
- cms del to de
=> IVYPORTAL-17669-Case-Details-DataTable-paginator-typo_RELEASE_LE

AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_es.yaml
- cms vom to von
- cms del to de
=> IVYPORTAL-17669-Case-Details-DataTable-paginator-typo_RELEASE_10

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskActionTest.java
- fix TaskActionTest due to wrong word
=> cicd-fix-task-action-test

Showcase/InternalSupport/processes/Business Processes/testProcesses/TestTaskFlow.p.json, Showcase/InternalSupport/src_hd/internaltest/ui/SaleDepartment/SaleDepartment.xhtml
=> IVYPORTAL-17214 Portal LE breadcrumb not display on some task

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetActionTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskActionTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskFilterTest.java
- fix failed tests due to wrong word
=> IVYPORTAL-17699-cicd-release_10

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/express/AdhocExpressTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskTemplateTest.java
- fix DashboardWelcomeWidgetTest
- fix TaskTemplateTest
- fix AdhocExpressTest
=> IVYPORTAL-17699-cicd-fix-failed-test_LE

AxonIvyPortal/portal/processes/SynchronizeDataProcesses/CleanUpObsoletedUserData.p.json, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CronByGlobalVariableTriggerStartEventBean.java
…ly restart (null pmv version)
- Add back Clean up bean
=> IVYPORTAL-17644-add-back-CronByGlobalVariableTriggerStartEventBean

AxonIvyPortal/PortalKitTestHelper/processes/Start Processes/Showcases.p.json, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/MenuTest.java
- fix failed GUI tests due to remove Showcases process
=> cicd-fix-fail-GUI_test_LE

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/MenuTest.java
=> IVYPORTAL-17699-fix-failed-test-on_RELEASE-10

build/gui-test-new-dashboard/Jenkinsfile
- implement showing problematic tests for selenium tests
=> IVYPORTAL-17687-showing-flaky-test-on-result_RELEASE_10

Documentation/portal-guide/source/portal-developer-guide/architecture/index.rst
=> IVYPORTAL-16535: Update doc - only run one portal per security context

AxonIvyPortal/portal-selenium-test/resources/extractFlakyTests.sh, build/gui-test-new-dashboard/Jenkinsfile
- implement new way to show flaky tests
=> IVYPORTAL-17687-showing-flaky-test-release-10

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalProcessesScreenshotTest.java
- fix screenshot test adapt UIFacelift
=> IVYPORTAL-17765-Release-fix-screenshot_LE

Documentation/maven/pom.xml
This reverts commit a25f5fb6852111256361969b94f9f5aa8a7d12a1.
=> Revert "Update pom.xml (#1110)"

Documentation/maven/pom.xml
This reverts commit e80dbf07c621e0bf1623c8ab60d01b8db3d8474b.
=> Revert "Update revision tag in pom.xml to 12.0.0-m265 (#1112)"

AxonIvyPortal/PortalKitTestHelper/.settings/ch.ivyteam.ivy.designer.prefs, AxonIvyPortal/portal-components/.settings/ch.ivyteam.ivy.designer.prefs, AxonIvyPortal/portal/.settings/ch.ivyteam.ivy.designer.prefs, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/AccessibilityShortcut/AccessibilityShortcutData.d.json, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/AccessibilityShortcut/AccessibilityShortcutProcess.p.json, Showcase/InternalSupport/.settings/ch.ivyteam.ivy.designer.prefs, Showcase/portal-components-examples/.settings/ch.ivyteam.ivy.designer.prefs, Showcase/portal-developer-examples/.settings/ch.ivyteam.ivy.designer.prefs, Showcase/portal-user-examples/.settings/ch.ivyteam.ivy.designer.prefs
=> IVYPORTAL-17796-convert-Portal-LE-21-10

AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json, AxonIvyPortal/portal/webContent/resources/js/portal.js
=> IVYPORTAL-17533 Create Accessibility Mode Dashboard Template

AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json, AxonIvyPortal/portal/webContent/resources/js/portal.js
fix issue highlight 2 menu items
=> IVYPORTAL-17533 Create accessibility mode dashboard template:

AxonIvyPortal/portal/webContent/resources/css/utility.css, AxonIvyPortal/portal/webContent/resources/js/dashboard.js
=> IVYPORTAL-17540 Implement column width changing for portal widgets 10

AxonIvyPortal/portal/src/com/axonivy/portal/bean/NotificationBean.java, AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/NotificationFullPage/NotificationFullPage.xhtml
Add new function to start task from notification full page
=> IVYPORTAL-17912 Fix invalid function startTaskFromNoti in Notification Full Page

AxonIvyPortal/PortalKitTestHelper/src/ch/ivy/addon/portalkit/test/util/TaskUtils.java, AxonIvyPortal/portal/webContent/resources/js/portal.js
- Use optional chaining operator to bypass error
=> IVYPORTAL-17212 Portal LTS breadcrumb error

AxonIvyPortal/portal/src/com/axonivy/portal/dto/dashboard/filter/DashboardFilter.java, Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst, Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-task-widget.rst
…ime-import-not-working - Fix import with time error
=> IVYPORTAL-17944 Fix bug Portal.DateTimeFormat.DateFilterWithTime import not working

AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/AbstractColumn.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml, AxonIvyPortal/portal/webContent/resources/css/dashboard.css
…ORTAL-17978 Bug custom field column width auto resize
- Fixed for LE
=> IVYPORTAL-17978 Bug custom field column width auto resize

AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/RegisteredApplicationService.java
- Fix reorder application doesn't work
=> IVYPORTAL-17822-LTS-Testing-Buffer-Story-can-not-reorder-admin-setting

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/GlobalSearch/GlobalSearch.xhtml
=> IVYPORTAL-17721 Quick search UI/UX behavior not perfect

AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/TaskColumnModel.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskDashboardExporter.java
This reverts commit 5731fb7036b8386e99a92ef19df1dd727e3e01a1.
=> Revert "IVYPORTAL-17763: Fix display case customfield on task widget"

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/GlobalSearchResultPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
- fix openTaskTab
- use parent to identify the task tab since old selector can select other hidden task tab
=> fix-testQuickGlobalSearch

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/FullProcessPageTest.java
=> fix-testEditDeleteProcessIcon

Documentation/portal-guide/source/portal-user-guide/accessibility/index.rst
=> IVYPORTAL-18011 Create accessibility documentation for LE

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java, AxonIvyPortal/portal/webContent/resources/js/dashboard.js
…ORTAL-17725 Column header highlight bug
- Fixed bug
=> IVYPORTAL-17725: Multiple headers are highlighted after sort

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardTaskWidgetBean.java
- Fixed highlight menu after finished task in full task list
=> IVYPORTAL-17982 Various or urgent requests in IVYPORTAL - S268

AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
=> IVYPORTAL-17937 Accessibility Dashboard - Case widget column has a vertical dash

AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
=> IVYPORTAL-17937 [Accessibility Dashboard] Case widget column has a vertical dash LE

Documentation/maven/pom.xml
Reverts axonivy-market/portal#1271
=> Revert "Release 12.0.0"

AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js
=> IVYPORTAL-17571-Remove-unused-function-in-document-screenshot.js-MASTER

AxonIvyPortal/portal/webContent/resources/css/module.css
- improve Action step alignment
=> IVYPORTAL-17938-Action-step-dropdown-so-bad-alignment

AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DemoProcessesScreenshotTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseMapPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/LeaveRequestPage.java
=> IVYPORTAL-18045-Check-and-beautify-screenshot_RELEASE_10

Documentation/maven/pom.xml
Reverts axonivy-market/portal#1293
=> Revert "Release 12.0.1"

AxonIvyPortal/portal/webContent/resources/js/chat.js, AxonIvyPortal/portal/webContent/resources/js/welcome-widget.js
=> IVYPORTAL-18031 Medium - DOM text reinterpreted as HTML

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseEditWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskEditWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardEditCaseWidgetTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardEditTaskWidgetTest.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml, build/document-screenshot-selenide/Jenkinsfile
- implement default sort in edit widget
- update GUI tests
- handle multiple ajax call in resizing mode
=> IVYPORTAL-18063-bring-back-default-sort-for-task-case-widget-LE (#1301)

AxonIvyPortal/PortalKitTestHelper/dataclasses/portalKit_test/DataCreationData.d.json, AxonIvyPortal/PortalKitTestHelper/processes/Start Processes/DataCreation.p.json
- Create a a business case has 50 technical cases, each technical case has 100 tasks
=> feature/IVYPORTAL-18068 Update test data of performance test engine

AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, Documentation/portal-guide/source/portal-user-guide/full-case-list/index.rst, Documentation/portal-guide/source/portal-user-guide/full-task-list/index.rst
=> IVYPORTAL-18073 Create file preview for PDF .log and PNG

build/Dockerfile
=> IVYPORTAL-18205 Fix build: performance master

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskIFrameTemplatePage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/BackNavigationTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetFilterTest.java
* IVYPORTAL-18153 Fix GUI tests
(cherry picked from commit cebde2a5d0af17b3cd1d91cefe6307250fcc49a5)
=> IVYPORTAL-18153 Fix GUI tests (#1320)

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/NotificationScreenshotTest.java
(cherry picked from commit 517c6e9dae15b02df67c66cd43cbc122ee222b55)
=> IVYPORTAL-18222: Fixed notification screenshot test (#1354)

Documentation/maven/pom.xml
Reverts axonivy-market/portal#1359
=> Revert "Update pom.xml for documentation release S269"

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardDetailModification.xhtml, AxonIvyPortal/portal/webContent/resources/css/dashboard.css
- disable dashboard link in Dashboard Detail Modification page
=> IVYPORTAL 18249 disable dashboard link LE

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardDetailModification.xhtml
=> IVYPORTAL-18249-Enhance-statistics-dashboard-modification-LTS12

Showcase/portal-developer-examples/config/users.xml
(cherry picked from commit d0af1937663b6dfef09ab4e58fd3be26721092de)
=> IVYPORTAL-14337: Upgrade Example Users (#1369)

AxonIvyPortal/portal/webContent/resources/js/portal.js
(cherry picked from commit 8f7162c65ce044ff992857b601cd369e16867964)
=> IVYPORTAL-17710: Able use shortcut in iframe (#1332)

AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CompactProcessWidgetBean.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/ProcessInformation/ProcessInformation.xhtml, AxonIvyPortal/portal/webContent/resources/css/utility.css
- Disable the start button whenever user try to start a restricted process
=> IVYPORTAL-18309 Error when try to run a restricted process from the Process Overview page

AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java, AxonIvyPortal/portal-components/webContent/resources/components/avatar.xhtml
…ORTAL-18316 Update the Avatar component to auto convert email to lower cases
- Implement
=> IVYPORTAL-18316 Update the Avatar component to auto convert email to lower cases for 12

AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java, AxonIvyPortal/portal-components/webContent/resources/components/avatar.xhtml
…ORTAL-18316 Update the Avatar component to auto convert email to lower cases
- Implement
=> IVYPORTAL-18316 Update the Avatar component to auto convert email to lower cases for LE

AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
- Fixed error after add new attribute
=> IVYPORTAL-18316 Update the Avatar component to auto convert email to lower cases LE

AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
- Fixed error after add new attribute
=> IVYPORTAL-18316 Update the Avatar component to auto convert email to lower cases 12

AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
- Fixed error after add new attribute
=> IVYPORTAL-18316 Update the Avatar component to auto convert email to lower cases 10

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserMenuBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseActionBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskActionBean.java
…… (#1415)
(cherry picked from commit 1762963a1ff23d87f1fa912594f18fb0aeebb37e)
=> IVYPORTAL-18026 Long loading time for accessing case details of case has thousands of tasks

AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
- Fixed error after add new attribute
=> IVYPORTAL-18316: Update the Avatar component to auto convert email to lower cases

AxonIvyPortal/portal-components/cms/cms_de.yaml, AxonIvyPortal/portal-components/cms/cms_en.yaml, AxonIvyPortal/portal-components/cms/cms_es.yaml, AxonIvyPortal/portal-components/cms/cms_fr.yaml, AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/DocumentUploadBean.java, AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml, AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableData.d.json, AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/component/DocumentTableComponentPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/DocumentTableComponentTest.java, Documentation/portal-guide/source/portal-components/document-table/index.rst, Documentation/portal-guide/source/portal-components/documents/document_table_component_attributes.csv, Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/CustomizedDocumentTableExample/CustomizedDocumentTableExample.xhtml, Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/serenity/CustomizedDocumentTableExampleSerenity/CustomizedDocumentTableExampleSerenity.xhtml
…#1425)
* feature/IVYPORTAL-18158-Implement-File-Preview-to-Portal-Components
- Implement logic
- Implement UI
- Update cms
- update example
- update GUI test
- Handle unsupported file type
- adapt dialog size
=> feature/IVYPORTAL-18158 Implement File Preview to Portal Components 12

Documentation/maven/pom.xml
This reverts commit eb8b64c90a4f75a733aa8de6c4529aea1d65382d.
=> Revert "IVYPORTAL-18325 Update documentation pom to 13.1.0-m270 (#1471)"

build/update-pom/Jenkinsfile
=> bug/IVYPORTAL-18401 Added updating config for Express in update-pom build

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml, AxonIvyPortal/portal/webContent/resources/css/module.css
- adjust alignment in Edit External link dialog
=> IVYPORTAL 18243 Edit external link UI not align

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml, AxonIvyPortal/portal/webContent/resources/css/module.css
- adjust alignment in Edit External link dialog
=> IVYPORTAL 1824 Edit external link UI not align

AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/ProcessViewerUtils.java
…ess case
(cherry picked from commit 5b642d02fca0f6f88255fdad3d760b39569e1cba)
=> IVYPORTAL-17180 Enable Process Viewer for a sub case of a business case

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml, AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml, AxonIvyPortal/portal/webContent/resources/js/process-widget.js
- Use messageContainer property instead of class name in Primefaces
=> IVYPORTAL-18374 Enhance the function to show an error message on uploading files

Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
=> IVYPORTAL-17515 Copy Dashboard Widgets with all settings

AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
=> feature/IVYPORTAL-18244 Create external link dialog bug

Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
=> IVYPORTAL 18324 Support bussiness case customfield

AxonIvyPortal/PortalKitTestHelper/processes/Start Processes/DataCreation.p.json, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/BaseTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetTest.java, AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/TaskColumnModel.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardColumnFormat.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardColumnType.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskDashboardExporter.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/ExportUtils.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/TaskFilterFieldFactory.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ColumnManagement/FieldAdd.xhtml
- implement feature
- update GUI test
=> IVYPORTA 18324 Support bussiness case customfield

AxonIvyPortal/portal/webContent/resources/js/client-statistic.js
=> IVYPORTAL-18247 Statistic on dark mode enhancement 

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml, AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml, AxonIvyPortal/portal/webContent/resources/js/process-widget.js
- Udpate handle error message when uploading files function
=> feature/IVYPORTAL-18374 Enhance the function to show an error message on uploading files

AxonIvyPortal/portal/webContent/resources/js/dashboard.js
=> IVYPORTAL-18426 Improve resize body function - version 12

AxonIvyPortal/portal/webContent/resources/js/dashboard.js
=> IVYPORTAL-18426 Improve resize body function - version 10

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/WelcomeWidgetUtils.java
=> IVYPORTAL-18458 Bug on welcome widget

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ColumnManagement/FieldAdd.xhtml
- disable input field for displayName
=> IVYPORTAL 18403 Portal custom field display name

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardConfiguration/PortalDashboardConfiguration.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
- reset active dashboard when click on configure in dashboard list
=> IVYPORTAL 18266 Multiple highlighting on menu

AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java, AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml, AxonIvyPortal/portal/webContent/resources/css/dashboard.css
- Add tooltip showing search scope for quick search
=> IVYPORTAL-18417 Show search scope of quick search function

AxonIvyPortal/portal/webContent/layouts/restricted/IFrameTaskTemplate.xhtml, Documentation/portal-guide/source/portal-developer-guide/components/layout-templates.rst
=> IVYPORTAL-18533-JavaScript-injection-report_10

AxonIvyPortal/portal/webContent/layouts/restricted/IFrameTaskTemplate.xhtml, Documentation/portal-guide/source/portal-developer-guide/iframe/index.rst
=> IVYPORTAL 18533 JavaScript injection report

AxonIvyPortal/portal/webContent/resources/js/portal.js
=> IVYPORTAL-18408 Make quick global search enabled by default

AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/CaseSearchCriteria.java
- fix bug when click on caseWidgetInfo
=> IVYPORTAL 18419 Error on Dashboard Case Widget Information

AxonIvyPortal/portal-selenium-test/resources/testFile/Dashboard_Dashboard_Export.json, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseEditWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskEditWidgetNewDashBoardPage.java
(cherry picked from commit ccb529a11b0f0fa47ee684ec0edef2489f239c7f)
=> IVYPORTAL-18140 Cleanup css fix guitest (#1573)

Documentation/portal-guide/source/portal-developer-guide/permissions/index.rst, Documentation/portal-guide/source/portal-developer-guide/settings/index.rst
=> document/IVYPORTAL 18399 Case Owner Can Delegate Tasks

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
=> IVYPORTAL-18557: Add paginator template for document table in case details

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
=> IVYPORTAL-18557 Add paginator template for document table in case details

AxonIvyPortal/portal-components/webContent/resources/components/securityMemberNameAndAvatar.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/NameCell.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/NameCell.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseCustomField/CaseCustomField.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseDate/CaseDate.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseId/CaseId.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseName/CaseName.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskCustomField/TaskCustomField.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskDate/TaskDate.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskId/TaskId.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskName/TaskName.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskPriority/TaskPriority.xhtml, Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/customization/CaseWidget/CaseWidget.xhtml, Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/customization/TaskWidget/TaskWidget.xhtml
- implement missing tooltip for Task/Case widget
- implement missing tooltip for Related Task/Case in Task/Case Details
=> IVYPORTAL 18546 Text overflow not consistently replaced with ellipsis and no consistent tool tips available

AxonIvyPortal/portal-components/.classpath, AxonIvyPortal/portal-components/webContent/resources/components/securityMemberNameAndAvatar.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/NameCell.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/NameCell.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseCustomField/CaseCustomField.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseDate/CaseDate.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseId/CaseId.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseName/CaseName.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskCustomField/TaskCustomField.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskDate/TaskDate.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskId/TaskId.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskName/TaskName.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskPriority/TaskPriority.xhtml
- implement missing tooltip for Task/Case widget
- implement missing tooltip for Related Task/Case in Task/Case Details
- adding more tool tip in FullTask/case List
=> IVYPORTAL 18546 Text overflow not consistently replaced with ellipsis and no consistent tool tips available (#1570)

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
=> IVYPORTAL 18546 Text overflow not consistently etc

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/GlobalGrowlTest.java
- fix failed test for integration
=> fix-test-for-release-10.0.26

Documentation/maven/pom.xml
- update revision pom.xml to 10.0.26
=> IVYPORTAL 18602 release 10.0.26 update pom.xml

Documentation/maven/pom.xml
This reverts commit 05f91f932e06161b82e782e96a085a9a2a1fa307.
=> Revert "IVYPORTAL-18602-release-10.0.26-update-pom.xml (#1599)"

Documentation/maven/pom.xml
- update revision to 10.0.27-SNAPSHOT
=> IVYPORTAL-18602-update-pom.xml-to-10.0.27-SNAPSHOT

build/document-screenshot-selenide/Jenkinsfile, build/gui-test-new-dashboard/Jenkinsfile
- remove cron for screenshot
- update cron for selenium to 21:00 (04:00 VN time)
=> IVYPORTAL-18611: Update cron for selenium and screenshot tests

Documentation/maven/pom.xml
=> release-Portal-12.0.4-update-revision

Documentation/maven/pom.xml
- update pom.xml to 12.0.5-SNAPSHOT
=> IVYPORTAL-18603-update-revision-to-12.0.5-SNAPSHOT

AxonIvyPortal/PortalApp/pom.xml, AxonIvyPortal/PortalKitTestHelper/pom.xml, AxonIvyPortal/portal-components/pom.xml, AxonIvyPortal/portal-migration/pom.xml, AxonIvyPortal/portal-product/pom.xml, AxonIvyPortal/portal-selenium-test/customized_pom.xml, AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml, AxonIvyPortal/portal-selenium-test/pom.xml, AxonIvyPortal/portal/pom.xml, Documentation/public-api/pom.xml, Showcase/InternalSupport/pom.xml, Showcase/portal-components-examples/pom.xml, Showcase/portal-demo-app/pom.xml, Showcase/portal-developer-examples/pom.xml, Showcase/portal-user-examples/pom.xml
- update pom.xml to 12.0.5-SNAPSHOT
=> Updated all pom build.plugin.version=, ivy.engine.version=, version=12.0.5-SNAPSHOT

Documentation/maven/pom.xml
- update revision to 13.1.0-m272
=> IVYPORTAL-18632-Release-13.1.0-m272-UPDATE-POM

Documentation/maven/pom.xml
This reverts commit eca186e65af76f5dd14dcf3250265cbeaf90bf77.
=> Revert "IVYPORTAL-18632-Release-13.1.0-m272-UPDATE-POM (#1626)"

AxonIvyPortal/PortalKitTestHelper/processes/Start Processes/GrantPermissions.p.json, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskActionBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/PortalPermission.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CaseUtils.java, Documentation/portal-guide/source/portal-developer-guide/permissions/index.rst, Documentation/portal-guide/source/portal-developer-guide/settings/index.rst
- Create new permission CaseOwnerTaskDelegate
- Update document
=> IVYPORTAL-18399 Case owner can delegate related tasks of case

build/gui-test-new-dashboard/Jenkinsfile
=> IVYPORTAL-18363 Remove trigger by change

AxonIvyPortal/portal-components/.classpath, AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-case-widget-has-quicksearch.json, AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-task-widget-has-quicksearch.json, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/BaseTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/QuickSearchTest.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/AbstractColumn.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/ColumnModel.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CaseColumnModel.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/TaskColumnModel.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardCaseSearchCriteria.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/WidgetFilterService.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/PortalCustomFieldUtils.java, AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/WidgetTextFilterBean.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/custom/CaseFilterFieldCustomString.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/custom/TaskFilterFieldCustomString.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/caze/customfield/CustomStringContainsOperatorHandler.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/caze/customfield/CustomStringInOperatorHandler.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/customfield/CustomStringContainsOperatorHandler.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/customfield/CustomStringInOperatorHandler.java, AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/TextFilter/TextFilter.xhtml, Showcase/portal-developer-examples/cms/cms_de.yaml, Showcase/portal-developer-examples/cms/cms_en.yaml, Showcase/portal-developer-examples/cms/cms_es.yaml, Showcase/portal-developer-examples/cms/cms_fr.yaml, Showcase/portal-developer-examples/config/custom-fields.yaml, Showcase/portal-developer-examples/processes/Start Processes/CreateTestData.p.json, build/gui-test-new-dashboard/Jenkinsfile
- Add new attribute HasCmsValue in custom-field.yaml file to allow multi language on content of custom field, only support for STRING
=> IVYPORTAL-17382 Multi Language support for Custom field

AxonIvyPortal/portal-components/src/com/axonivy/portal/components/publicapi/SanitizeAPI.java, Documentation/portal-guide/source/portal-developer-guide/components/layout-templates.rst
- Added public API to escape Javascript String
- Updated document
=> IVYPORTAL-18559: Adapt documentation for sanitizing java script code

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
=> IVYPORTAL-18535 Dashboard cache issue in edit mode

AxonIvyPortal/portal/cms/cms_de.yaml, Showcase/portal-developer-examples/cms/cms_de.yaml
=> IVYPORTAL-18600 Update Translation in German

AxonIvyPortal/portal/webContent/resources/css/portal-variables-light.css
- Change background color of process item in process list compact mode
=> IVYPORTAL-18450-Process-list-in-compact-mode-background-color-of-item-is-not-nice

AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/cms/cms_ja.yaml, AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/AbsenceManagementBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/UserUtils.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/AbsenceManagement.xhtml
_ Add logic to show active absence
_ Adapt UI
=> IVYPORTAL-17305 List active absences in the absence management of the portal

AxonIvyPortal/portal/webContent/resources/css/portal.css
=> IVYPORTAL-18238 Related tasks of case table column not align

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardDetails/DashboardDetails.xhtml
=> feature/IVYPORTAL 18454 Not found message in Portal does not change by user language

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardDetails/DashboardDetails.xhtml
=> Feature/ivyportal 18454 Not found message in portal not change by language

Documentation/portal-guide/source/portal-components/index.rst
- Added note to mention that Serenity will be removed in Portal 13
=> IVYPORTAL-18554 Drop support for Serenity theme since 13.1

.github/workflows/cron-bot.yml, .github/workflows/portal-document-screenshot-test.yml, .github/workflows/portal-documentation.yml, build/gui-test-new-dashboard/Jenkinsfile, build/performance-test/Jenkinsfile
- update pollSCM to 12:00 VN time
=> IVYPORTAL-18611 Update cron for Portal builds

.github/workflows/portal-document-screenshot-test.yml, .github/workflows/portal-documentation.yml
- update name, run-name for screenshot, documentation builds
=> IVYPORTAL-18611 Update run name for Portal builds

Documentation/maven/pom.xml
This reverts commit dee0a726f2f2e7faa35c849c69500dc873dd94b1.
=> Revert "feature/Update-revision-documentation"

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/AdminSettingsPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
=> IVYPORTAL-18814 Fix unstable testcases LTS 10

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/CloneWidgetBean.java, AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml, AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
=> IVYPORTAL-18436 Analyze Performance Problems

AxonIvyPortal/portal/cms/cms.yaml, AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/cms/cms_ja.yaml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeDashboardWidget/WelcomeDashboardWidget.xhtml
- Add new alt attribute for welcome widget
=> IVYPORTAL-18601 Add value for alt attribute in welcome widget 12

AxonIvyPortal/portal/cms/cms.yaml, AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeDashboardWidget/WelcomeDashboardWidget.xhtml
=> IVYPORTAL-18601 Add value for alt attribute in welcome widget 10

Documentation/portal-guide/source/portal-developer-guide/dashboard/index.rst, Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-navigation-dashboard-widget.rst, Documentation/portal-guide/source/portal-user-guide/dashboard-configuration/index.rst, Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
=> IVYPORTAL-18692: Navigation Dashboard Widget

AxonIvyPortal/portal-components/cms/cms_de.yaml, AxonIvyPortal/portal-components/cms/cms_en.yaml, AxonIvyPortal/portal-components/cms/cms_es.yaml, AxonIvyPortal/portal-components/cms/cms_fr.yaml, AxonIvyPortal/portal-components/cms/cms_ja.yaml, AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java, AxonIvyPortal/portal-components/src/com/axonivy/portal/components/enums/GlobalVariable.java, AxonIvyPortal/portal-components/webContent/resources/components/securityMemberNameAndAvatar.xhtml, AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/cms/cms_ja.yaml, AxonIvyPortal/portal/config/variables.yaml, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml, AxonIvyPortal/portal/webContent/resources/css/module.css, AxonIvyPortal/portal/webContent/resources/css/portal.css, Documentation/portal-guide/source/portal-components/documents/security_member_name_and_avatar_component_attributes.csv, Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
- prevent case/task details auto expand height.
- implement to show technical tooltip name.
- update documentation.
=> IVYPORTAL-18545 Columns get hidden automatically when using the case details

build/integration/Jenkinsfile
* IVYPORTAL-18888 Fix integration failed build
(cherry picked from commit 0988a03e57a84a819fa326799545544227b01bec)
=> Feature/ivyportal 18888 update integration build (#1733)

build/integration/Jenkinsfile
* IVYPORTAL-18888 Fix integration failed build
(cherry picked from commit 0988a03e57a84a819fa326799545544227b01bec)
=> IVYPORTAL-18888 Fix integration failed build

Documentation/maven/pom.xml
- Update documentation reversion
=> IVYPORTAL-18902 Create release 12.0.5

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardConfigurationTest.java
This reverts commit 126e80802b9d888b4987cbe04ca30051917ef34d.
=> IVYPORTAL-18904-Fix-GUI-test

Documentation/maven/pom.xml
This reverts commit ab8939c23f73fb78710ca6db06dd66e1104a6f6e.
=> Revert "Update revision"

AxonIvyPortal/portal/cms/cms.yaml, AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/cms/cms_ja.yaml, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseWidgetBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskDetailsBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskWidgetBean.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/ActionsCell.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/ActionsCell.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItem/CaseItem.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/TaskAction.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseWidget/CaseWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SideStep/SideStep.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItem/TaskAction.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItem/TaskItem.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDetails/TaskItemDetails.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskWidget/TaskWidget.xhtml, AxonIvyPortal/portal/webContent/layouts/PortalTaskDetailsTemplate.xhtml, AxonIvyPortal/portal/webContent/layouts/SearchResultsTemplate.xhtml, AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
- Adapt for Task widget, task details, global search result
- Adapt for Case widget, case details, case related task, global search result
=> Feature/ivyportal 18795 Show more information destroy and reset dialog

AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CaseTreeUtils.java
=> IVYPORTAL-18555 Case category filter doesn't respect CaseReadAll permission

AxonIvyPortal/portal/cms/cms.yaml, AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/cms/cms_ja.yaml, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseWidgetBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskDetailsBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskWidgetBean.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/ActionsCell.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/ActionsCell.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItem/CaseItem.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/TaskAction.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseWidget/CaseWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SideStep/SideStep.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItem/TaskAction.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItem/TaskItem.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDetails/TaskItemDetails.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskWidget/TaskWidget.xhtml, AxonIvyPortal/portal/webContent/layouts/SearchResultsTemplate.xhtml, AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
Show more information destroy dialog
=> Feature/ivyportal 18795 Show more information destroy dialog

AxonIvyPortal/portal/src/com/axonivy/portal/bean/StatisticConfigurationBean.java, AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/WidgetCreatorFilterBean.java, AxonIvyPortal/portal/src/com/axonivy/portal/bo/StatisticAggregation.java, AxonIvyPortal/portal/src/com/axonivy/portal/constant/StatisticConstants.java, AxonIvyPortal/portal/src/com/axonivy/portal/dto/dashboard/filter/BaseFilter.java, AxonIvyPortal/portal/src/com/axonivy/portal/dto/statistic/StatisticFilter.java, AxonIvyPortal/portal/src/com/axonivy/portal/enums/statistic/AggregationInterval.java, AxonIvyPortal/portal/src/com/axonivy/portal/service/StatisticService.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/CaseFilterFieldCreator.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/statisticfilter/field/CaseFilterFieldFactory.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/statisticfilter/field/caze/CaseFilterFieldCategory.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/statisticfilter/field/caze/CaseFilterFieldCreator.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/statisticfilter/field/caze/CaseFilterFieldState.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/statisticfilter/field/task/TaskFilterFieldResponsible.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/statisticfilter/operator/text/TextInOperatorHandler.java, AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/CreatorFilter/CreatorFilter.xhtml, AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/StatisticConfiguration/StatisticConfiguration.xhtml, AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/component/StatisticFilter/StatisticFilter.xhtml, AxonIvyPortal/portal/webContent/resources/js/statistic.js
=> IVYPORTAL-18402-Create-the-JSON-structure-aggregation

AxonIvyPortal/portal/cms/cms.yaml, AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseWidgetBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskActionBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskDetailsBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskWidgetBean.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseDashboardWidget/CaseDashboardWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/ActionsCell.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskDashboardWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/ActionsCell.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItem/CaseItem.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/TaskAction.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseWidget/CaseWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SideStep/SideStep.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItem/TaskAction.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItem/TaskItem.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDetails/TaskItemDetails.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskWidget/TaskWidget.xhtml, AxonIvyPortal/portal/webContent/layouts/SearchResultsTemplate.xhtml, AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml, build/gui-test-new-dashboard/Jenkinsfile
- Show more information in destroy dialog
=> Feature/ivyportal 18795 Show more information in destroy dialog

AxonIvyPortal/portal/cms/cms_en.yaml
=> portal-cms-1

AxonIvyPortal/portal/cms/cms_en.yaml
=> portal-cms-2

AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/cms/cms_ja.yaml, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/MasterDataBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java, Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
=> Feature/ivyportal 18929 Portal page title update

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardFilterWidgetTest.java, AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/CaseWidgetUserFilterBean.java, AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/TaskWidgetUserFilterBean.java, AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/CategoryFilter/CategoryFilter.xhtml
- fix category filter can't remove in normal mode
=> IVYPORTAL-18910 Cannot remove filter category of task widget and case widget

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardFilterWidgetTest.java, AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/CaseWidgetUserFilterBean.java, AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/TaskWidgetUserFilterBean.java, AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/CategoryFilter/CategoryFilter.xhtml
- fix category filter can't remove in normal mode
- adding GUI test
=> IVYPORTAL-18910 Cannot remove filter category of task_case widget

AxonIvyPortal/portal-selenium-test/jmeter/portal_walkthrough_testplan.jmx
=> IVYPORTAL-18007 Update performance test so that responses are as expected

AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsProcess.p.json, AxonIvyPortal/portal/webContent/resources/css/module.css, AxonIvyPortal/portal/webContent/resources/js/portal.js
=> IVYPORTAL-18828 Add Expand Button to File Preview

AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardCaseSearchCriteria.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
- Use less than or equal operator for date field in dashboard like in full case list
=> IVYPORTAL-18984 Dashboard case list and full case list are different

AxonIvyPortal/portal/cms/cms_de.yaml
=> IVYPORTAL-19010 Correct Spelling Error in CMS Note

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/IconSelection/IconSelection.xhtml
=> IVYPORTAL-18654: Fix accessibility problem related to icon selection

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/IconSelection/IconSelection.xhtml
=> IVYPORTAL-18654: Fix accessibility problem related to icon select

AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/PortalExceptionBean.java, AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/CanWorkOnFilter/CanWorkOnFilterProcess.p.json, AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/StatisticConfiguration/StatisticConfiguration.xhtml, AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/StatisticConfiguration/StatisticConfigurationProcess.p.json, AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/component/StatisticFilter/StatisticFilterProcess.p.json
- Udpated statistic accessibility lighthouse related heading order
- Converted project to latest ivy, commented out compile error to ease development
=> IVYPORTAL-18840 Portal 13.1 Quality Pass

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserMenuBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/PortalExceptionBean.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/error/ErrorPage/ErrorPage.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ExceptionDialog/ExceptionDialog.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/GlobalAjaxStatus/GlobalAjaxStatus.xhtml
=> IVYPORTAL-19012 Use errorPage bean to check condition to show error details

Documentation/portal-guide/source/portal-developer-guide/customization/portal-style-customization-logos-colors-date-patterns.rst
- Update example for style customization
=> IVYPORTAL-18923 Improve document for custom styles

AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
=> IVYPORTAL-18997 Issue with reset filters button in complex filter

AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js
- update createOutline in document-screenshot.js
=> IVYPORTAL-19017-Fix-Screenshots-n-GUI-tests

AxonIvyPortal/portal/config/variables/Portal/Statistic.json, Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-statistic-widget.rst, Documentation/portal-guide/source/portal-developer-guide/settings/index.rst
- update documentation statistic
=> IVYPORTAL-19017 update document statistic

build/update-pom/Jenkinsfile
=> IVYPORTAL-18840: Portal 13.1 Quality Pass

README.md
- Mention Weblate in Git repo to meet their requirement for Libre plan
=> feature/IVYPORTAL-18946: Integrate-Portal-into-Weblate

AxonIvyPortal/PortalApp/pom.xml, AxonIvyPortal/PortalKitTestHelper/pom.xml, AxonIvyPortal/portal-components/pom.xml, AxonIvyPortal/portal-product/pom.xml, AxonIvyPortal/portal-selenium-test/customized_pom.xml, AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml, AxonIvyPortal/portal-selenium-test/pom.xml, AxonIvyPortal/portal/pom.xml, Documentation/public-api/pom.xml, Showcase/InternalSupport/pom.xml, Showcase/portal-components-examples/pom.xml, Showcase/portal-demo-app/pom.xml, Showcase/portal-developer-examples/pom.xml, Showcase/portal-user-examples/pom.xml
…1, version=13.1.1-SNAPSHOT, parentVersion=13.1.0
=> Updated all pom version=13.1.1-SNAPSHOT, parentVersion=13.1.0

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
=> IVYPORTAL-18614 Dashboard json appear styleClass attribute

Showcase/portal-components-examples/processes/Functional Processes/CustomDocumentFeatures.p.json
=> IVYPORTAL-19144 Missing examples for customized document processes

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseDashboardWidget/CaseInfo.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessDashboardWidget/ProcessInfo.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskInfo.xhtml
- implement auto focus on Widgets information panel
=> IVYPORTAL-19044 Correct Focus Order on Tasks/Cases Page

AxonIvyPortal/portal/webContent/resources/js/statistic.js
- Improve formatChartLabel function
- Update check value is string or number
=> bug/IVYPORTAL-19191: Wrong label on statistic chart with numerical data

AxonIvyPortal/PortalKitTestHelper/.settings/ch.ivyteam.ivy.designer.prefs, AxonIvyPortal/PortalKitTestHelper/pom.xml, AxonIvyPortal/portal-components/.settings/ch.ivyteam.ivy.designer.prefs, AxonIvyPortal/portal-components/pom.xml, AxonIvyPortal/portal-selenium-test/.settings/ch.ivyteam.ivy.designer.prefs, AxonIvyPortal/portal-selenium-test/pom.xml, AxonIvyPortal/portal/.settings/ch.ivyteam.ivy.designer.prefs, AxonIvyPortal/portal/pom.xml, Showcase/InternalSupport/.settings/ch.ivyteam.ivy.designer.prefs, Showcase/InternalSupport/pom.xml, Showcase/portal-components-examples/.settings/ch.ivyteam.ivy.designer.prefs, Showcase/portal-components-examples/pom.xml, Showcase/portal-developer-examples/.settings/ch.ivyteam.ivy.designer.prefs, Showcase/portal-developer-examples/pom.xml, Showcase/portal-user-examples/.settings/ch.ivyteam.ivy.designer.prefs, Showcase/portal-user-examples/pom.xml
=> IVYPORTAL-19204 Create release 13.1.1

AxonIvyPortal/portal/webContent/resources/js/client-statistic.js
- Enhance function formatChartLabel
=> IVYPORTAL-19191: Wrong label in statistic charts with numerical data

AxonIvyPortal/portal/webContent/resources/js/statistic.js
- Update check value is string or number
- Remove unuse functions
=> IVYPORTAL-19191: Wrong label on statistic chart with numerical data

AxonIvyPortal/portal/webContent/resources/js/client-statistic.js
- update label when number chart is empty
=> IVYPORTAL-19191 adapt when number label empty task

.github/workflows/portal-document-screenshot-test.yml
- update actions version
- remove ref version when checkout branch
=> IVYPORTAL-19217 Update Github action for screenshots

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
This reverts commit 7341e89cb2a2d0efca9bc86a6178e67599a42f0b.
=> Revert "IVYPORTAL-19091 Fixed unstalbe test (#2193)"

AxonIvyPortal/portal/webContent/resources/js/global-search.js
=> IVYPORTAL-19203 Quick search duplicate api call

AxonIvyPortal/portal/webContent/resources/js/global-search.js
=> IVYPORTAL-19203 Quick search duplicate api call LTS 12

AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DemoProcessesScreenshotTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ExampleOverviewPage.java
=> IVYPORTAL-19212 Improve document screenshot

AxonIvyPortal/portal/webContent/resources/js/portal.js
=> IVYPORTAL-19252 Improve aria label in Portal left menu

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DemoProcessesScreenshotTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalCasesScreenshotTest.java
- extend screen width for better screenshot
- improve case-key-information.png
- improve lending-casemap-external-solvency-service.png
=> IVYPORTAL-19220 Improve document screenshot

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
=> IVYPORTAL-19301 Improve column management dialog

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/Absence.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessListMode.xhtml, AxonIvyPortal/portal/webContent/layouts/restricted/decorator/SidebarWidgetConfiguration.xhtml, AxonIvyPortal/portal/webContent/resources/css/portal.css, AxonIvyPortal/portal/webContent/resources/js/notification.js
- align fields in add absence dialog
- increase width of notification panel to avoid breaking in French
- add edit button for processes created with external link in compact mode
- remove unnecessary space in edit widget configuration
=> IVYPORTAL-19142 UI findings

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
- Remove step simplifyColumnsData because it already done when saving widget in DashboardDetailModificationBean
=> bug/IVYPORTAL-19248: Columns-field-disappear-in-dashboard-JSON-file-after-adding-new-field-in-widget

AxonIvyPortal/portal/webContent/layouts/BasicTemplate.xhtml, AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml, AxonIvyPortal/portal/webContent/resources/css/dashboard.css, AxonIvyPortal/portal/webContent/resources/css/module.css, AxonIvyPortal/portal/webContent/resources/js/portal.js
=> IVYPORTAL-19177 Advance UI findings

AxonIvyPortal/portal-selenium-test/resources/testFile/custom-case-details.json, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/AbstractConfigurableContentBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/constant/WidgetType.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/widget/AbstractWidget.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/widget/BusinessDetailsWidget.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/CustomWidgetParam.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CustomWidgetUtils.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/UrlUtils.java, AxonIvyPortal/portal/src/com/axonivy/portal/util/BusinessDetailsUtils.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemBusinessDetails/CaseItemBusinessDetails.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemBusinessDetails/CaseItemBusinessDetailsData.d.json, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemBusinessDetails/CaseItemBusinessDetailsProcess.p.json, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml, AxonIvyPortal/portal/webContent/resources/js/case-details.js, Documentation/portal-guide/source/portal-developer-guide/customization/case-item-details.rst, Showcase/portal-developer-examples/resources/files/variables.Portal.CaseDetails.json, Showcase/portal-user-examples/processes/Business Processes/CreateTestData.p.json, Showcase/portal-user-examples/src_hd/com/axonivy/portal/userexamples/CustomWidgetNote/CustomWidgetNoteProcess.p.json
(cherry picked from commit 512cc6dccb701db57a32b1e0b76f9448f7379144)
=> IVYPORTAL-18926 Show business detail directly in case detail (#2200)

AxonIvyPortal/portal/cms/cms.yaml, AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/UserProfile/UserProfile.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseWidget/CaseWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskWidget/TaskWidget.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/taskwidget/ActivatorFilterColumn/ActivatorFilterColumn.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/taskwidget/PriorityFilterColumn/PriorityFilterColumn.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/taskwidget/StateFilterColumn/StateFilterColumn.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/widget/NumberFilterColumn/NumberFilterColumn.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/widget/TextFilterColumn/TextFilterColumn.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/widget/TimestampFilterColumn/TimestampFilterColumn.xhtml
=> IVYPORTAL-19305 Enhance My Profile accessibility

AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
=> IVYPORTAL-19372 Document Table - empty File Preview

AxonIvyPortal/portal-components/webContent/resources/css/security-member-avatar-component.css, AxonIvyPortal/portal/webContent/resources/css/module.css
=> IVYPORTAL-19451 Issue with displaying the avatar of the responsible on related tasks of a case

.github/workflows/portal-documentation-weblate.yml
- Update workflow file to add languages files for de, fr, es
=> IVYPORTAL-19240 Integrate Portal Documentation into Weblate

AxonIvyPortal/portal/webContent/resources/js/iframe-task-template.js
We are improving some redirection logic in ivy core and because of it `redirect.xhtml` has been removed. Instead we directly return the content that used to be on that `redirect.xhtml` page as a response on the `end`.
We also added new prefix for the default pages redirects, which is `/go` that's why there is a check for `/go/end`
=> XIVY-17263 Adjust frame redirection logic to match new core changes

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/Variable.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskDetailsTest.java, AxonIvyPortal/portal/cms/cms_de.yaml, AxonIvyPortal/portal/cms/cms_en.yaml, AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml, AxonIvyPortal/portal/cms/cms_ja.yaml, AxonIvyPortal/portal/config/variables.yaml, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/GlobalSettingService.java, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemHistory/CaseItemHistory.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemHistory/CaseItemHistoryProcess.p.json, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemNotes/TaskItemNotes.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemNotes/TaskItemNotesProcess.p.json, Documentation/portal-guide/source/portal-user-guide-japanese/admin-settings/documents/available_settings.csv, Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
- implement check system notes/tasks in case/task details by default
=> IVYPORTAL-18976 Filter system task

build/gui-test-new-dashboard/Jenkinsfile
=> IVYPORTAL-19593 Disable Jenkins Selenium Test MASTER

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/MainMenuPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/SystemNoteVisibilityTest.java
=> IVYPORTAL-19594 Stabilize test for release

AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/DashboardTaskService.java
- Adding missing logic
(cherry picked from commit b887b9ba70cfd04bb557108eb99ff4afbebb3f18)
=> IVYPORTAL-19088 Check filter system task by permission (#2425)

AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml, AxonIvyPortal/portal/webContent/resources/js/portal.js
- Adding script in AbstractTaskTemplate
=> IVYPORTAL-19442 Collapsed menu not readable by screen reader in task

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/MainMenuPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NoteHistoryPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/EnhanceVisibilityTasksForMemberOfRoleTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/SystemNoteVisibilityTest.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java
=> IVYPORTAL-19604 Stabilize Selenium tests

AxonIvyPortal/portal/cms/cms_es.yaml, AxonIvyPortal/portal/cms/cms_fr.yaml
=> IVYPORTAL-19324 Menu dashboard title does not have multi language

AxonIvyPortal/portal-components/processes/Functional Processes/GetDocumentItems.p.json, AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json, AxonIvyPortal/portal/processes/Functional Processes/GetDocumentList.p.json, Documentation/portal-guide/source/portal-components/document-table/index.rst, Showcase/portal-components-examples/processes/Functional Processes/CustomDocumentFeatures.p.json
- Update DocumentTable component to use uuid
- Update documentation
=> IVYPORTAL-19348 Updating document table component to use UUID

AxonIvyPortal/portal/cms/cms_de.yaml
- Update cms of "Share" from "Aktie" to "Teilen"
=> IVYPORTAL-19542 Correct German wording for "Share" label

AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/DashboardWidgetExporter.java, AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java, AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/AbstractTaskWidgetFilterBean.java
- When adding two custom fields which are the same name, duplicate key error appears
=> IVYPORTAL-19589 Duplicate key error when adding custom fields in task widget

AxonIvyPortal/portal/webContent/resources/css/dashboard.css
=> IVYPORTAL-19408 Dashboard Widget Table Header Not Algin Correctly

AxonIvyPortal/portal-components/cms/cms.yaml, AxonIvyPortal/portal-components/cms/cms_de.yaml, AxonIvyPortal/portal-components/cms/cms_en.yaml, AxonIvyPortal/portal-components/cms/cms_es.yaml, AxonIvyPortal/portal-components/cms/cms_fr.yaml, AxonIvyPortal/portal-components/cms/cms_ja.yaml, AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/DocumentUtils.java, AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml, AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentProcess.p.json, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml, AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsProcess.p.json
=> IVYPORTAL-19633 Cannot rename document after preview

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/component/DocumentTableComponentPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/DocumentTableComponentTest.java
=> IVYPORTAL-19604 Stabilize DocumentTableComponentTest

AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/AbsencePage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/StatisticConfigurationPage.java, AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
- improve how-to-add-task-note.png
=> IVYPORTAL-19671 Improve not so good screenshots

Documentation/maven/pom.xml
This reverts commit 57dfb6e17c6dd0662edcb24e5e0a5e1e57e0a832.
=> Revert "IVYPORTAL-19666 Update pom to 13.2.0-m281 (#2561)"

AxonIvyPortal/portal/webContent/resources/css/dashboard.css
=> IVYPORTAL-19625 Double scroll bars appearing in Task and Case tables
